# Generated by Django 4.2.30 on 2026-07-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0003_alter_quiz_options_quiz_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
